---
kind: pipeline
name: karrot

steps:
  - name: release
    image: plugins/docker
    settings:
      registry: docker.io
      repo: lowess/${DRONE_REPO_NAME}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_TAG}
    when:
      event: tag
