version: "2"
services:
  karrot:
    image: karrot
    build:
      context: ../
    environment:
      FLASK_APP: karrot.wsgi
      FLASK_ENV: production
    volumes:
      - ~/.aws:/root/.aws
    command:
      - "karrot:create_app()"
      - -b :5000
      - -w 4
    ports:
      - 5000:5000
    depends_on:
      - burrow
    restart: always

  burrow:
    image: solsson/burrow:latest
    volumes:
      - ${PWD}/config/dsci:/etc/burrow
    ports:
      - 8000:8000
    # depends_on:
    #   - zookeeper
    #   - kafka
    restart: always

  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - 2181:2181

  # kafka:
  #   image: wurstmeister/kafka:1.1.0
  #   ports:
  #     - 9092:9092
  #   environment:
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/local
  #     KAFKA_ADVERTISED_HOST_NAME: kafka
  #     KAFKA_ADVERTISED_PORT: 9092
  #     KAFKA_CREATE_TOPICS: "test-topic:2:1,test-topic2:1:1,test-topic3:1:1"
